version: '3.1'

services:
  app:
    container_name: automated_test
    image: golang:latest
    restart: always
    working_dir: /app
    command: go run main.go http
    ports:
      - 8080:8080
  app-tasks:
    container_name: automated_test-tasks
    image: golang:latest
    restart: always
    working_dir: /app
    command: go run main.go tasks
    ports:
      - 8080:8080
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
  influxdb:
    platform: linux/amd64
    image: influxdb:1.7-alpine
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=${INFLUXDB_USER:-prometheus}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-prompass}