// Code generated by SQLBoiler 4.10.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Datacenters         string
	Endpoints           string
	Projects            string
	RelationDatacenters string
	Schedulings         string
}{
	Datacenters:         "datacenters",
	Endpoints:           "endpoints",
	Projects:            "projects",
	RelationDatacenters: "relation_datacenters",
	Schedulings:         "schedulings",
}
