// Code generated by SQLBoiler 4.9.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Datacenters         string
	Endpoints           string
	NetCats             string
	PageSpeeds          string
	Pings               string
	Projects            string
	RelationDatacenters string
	Schedulings         string
	TraceRoutes         string
}{
	Datacenters:         "datacenters",
	Endpoints:           "endpoints",
	NetCats:             "net_cats",
	PageSpeeds:          "page_speeds",
	Pings:               "pings",
	Projects:            "projects",
	RelationDatacenters: "relation_datacenters",
	Schedulings:         "schedulings",
	TraceRoutes:         "trace_routes",
}
